#This solution, non-production-ready template describes AWS Codepipeline based CICD Pipeline for packer code deployment.
#© 2023 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
#This AWS Content is provided subject to the terms of the AWS Customer Agreement available at
#http://aws.amazon.com/agreement or other written agreement between Customer and either
#Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py"
      - "python3 get-pip.py"
      - "python3 -m pip install ansible"
      # - "curl -o jq-linux-amd64 https://github.com/jqlang/jq/releases/download/jq-1.7.1/jq-linux-amd64"
      # - "mv jq-linux-amd64 /usr/local/bin/jq"
      # - "chmod +x /usr/local/bin/jq"
      - "yum install -y jq"
      - "curl -s -qL -o mitogen.tar.gz https://files.pythonhosted.org/packages/source/m/mitogen/mitogen-${mitogen_version}.tar.gz"
      - "mv mitogen.tar.gz /opt; cd /opt; tar vxzf mitogen.tar.gz"
      - "curl -s -qL -o packer.zip https://releases.hashicorp.com/packer/${packer_version}/packer_${packer_version}_linux_amd64.zip"
      - "unzip -o packer.zip"
      - "mv packer /bin"
      - "rm packer.zip"
  build:
    commands:
      - echo "Configuring AWS credentials"
      - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
      - cat aws_credentials.json
      - aws configure set region $AWS_REGION
      - echo $(jq -r '.AccessKeyId' aws_credentials.json)
      - aws configure set aws_access_key_id $(jq -r '.AccessKeyId' aws_credentials.json)
      - export SecretAccessKey=$(python -c 'import sys; import json; print(json.loads(sys.stdin.read()).get('SecretAccessKey')')
      - aws configure set aws_secret_access_key ${SecretAccessKey}
      - aws configure set aws_session_token $(jq -r '.Token' aws_credentials.json)
      - echo "Building HashiCorp Packer template, ${packer_config}"
      - "cd $${CODEBUILD_SRC_DIR}/$${CODE_SRC_DIR}"
      - "/bin/packer init ${packer_config}"
      - "/bin/packer build ${packer_config}"

artifacts:
  files:
    - '**/*'