version: 0.2

env:
    variables:
        CODE_SRC_DIR: "."

phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - which pip3 || curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            - which pip3 || python3 get-pip.py --user
            - stat $(python -m site --user-base)/bin/ansible-playbook || python3 -m pip install --user ansible pywinrm
            - stat $(python -m site --user-base)/bin/ansible-playbook || exit 1
            - stat /bin/packer || curl -s -qL -o packer.zip https://releases.hashicorp.com/packer/${packer_version}/packer_${packer_version}_linux_amd64.zip
            - stat /bin/packer || unzip -o packer.zip
            - stat /bin/packer || $(mv packer /bin && rm packer.zip)

    build:
        commands:
            - echo "Configuring AWS credentials"
            - echo "Fetching AWS credentials from ECS metadata service"
            - echo "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}"
            - echo $${CODEBUILD_SRC_DIR_SourceAnsibleOutput}
            - curl -qL -o aws_credentials.json http://169.254.170.2/$${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI} > aws_credentials.json
            - aws configure set region $AWS_REGION
            - aws configure set aws_access_key_id `jq -r '.AccessKeyId' aws_credentials.json`
            - export AWS_ACCESS_KEY_ID=`jq -r '.AccessKeyId' aws_credentials.json`
            - aws configure set aws_secret_access_key `jq -r '.SecretAccessKey' aws_credentials.json`
            - export AWS_SECRET_ACCESS_KEY=`jq -r '.SecretAccessKey' aws_credentials.json`
            - aws configure set aws_session_token `jq -r '.Token' aws_credentials.json`
            - export AWS_SESSION_TOKEN=`jq -r '.Token' aws_credentials.json`
            - echo "Building HashiCorp Packer template, ${packer_config}"
            - cd $${CODEBUILD_SRC_DIR}/$${CODE_SRC_DIR}
            - /bin/packer init ${packer_config}
            - ln -s $${CODEBUILD_SRC_DIR_SourceAnsibleOutput}/roles
            - aws secretsmanager get-secret-value --secret-id ${ssh_private_key_secret_id} --query SecretString --output text > ${ssh_private_key_file}
            - echo '${required_packages}' > required_packages.json
            - /bin/packer build -var bucket=${bucket} -var project_name=${project_name} -var ansible_dir=$${CODEBUILD_SRC_DIR_SourceAnsibleOutput} -var ssh_private_key_file=${ssh_private_key_file} ${packer_config}
    post_build:
        commands:
            - cd $${CODEBUILD_SRC_DIR}/$${CODE_SRC_DIR}
            - test -s ami_id.txt || exit 1
artifacts:
    files:
        - '**/*'

cache:
  paths:
    - '/root/.config/**/*'
    - '/root/.local/**/*'
    - '/bin/packer'