version: 0.2

env:
    variables:
        CODE_SRC_DIR: "."

phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - stat $${CODEBUILD_SRC_DIR_SourceAnsibleOutput}/init.sh && bash $${CODEBUILD_SRC_DIR_SourceAnsibleOutput}/init.sh $${CODEBUILD_SRC_DIR_SourceAnsibleOutput} || echo "No init.sh script found"
            - apt-get install -y jq curl unzip
            - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${terraform_version}/terraform_${terraform_version}_linux_amd64.zip
            - unzip -o terraform.zip
            - mv terraform /bin
            - rm terraform.zip
    build:
        commands:
            - echo "Configuring AWS credentials"
            - echo "Fetching AWS credentials from ECS metadata service"
            - echo "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}"
            - curl -qL -o aws_credentials.json http://169.254.170.2/$${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI} > aws_credentials.json
            - aws configure set region $AWS_REGION
            - aws configure set aws_access_key_id `jq -r '.AccessKeyId' aws_credentials.json`
            - export AWS_ACCESS_KEY_ID=`jq -r '.AccessKeyId' aws_credentials.json`
            - aws configure set aws_secret_access_key `jq -r '.SecretAccessKey' aws_credentials.json`
            - export AWS_SECRET_ACCESS_KEY=`jq -r '.SecretAccessKey' aws_credentials.json`
            - aws configure set aws_session_token `jq -r '.Token' aws_credentials.json`
            - export AWS_SESSION_TOKEN=`jq -r '.Token' aws_credentials.json`
            - echo "Applying Terraform configuration template"
            - cd $${CODEBUILD_SRC_DIR_SourceGossOutput}
            - /bin/terraform init -upgrade # -backend-config="key=${state.key}" -backend-config="region=${state.region}" -backend-config="bucket=${state.bucket}" -backend-config="encrypt=true"
            - /bin/terraform apply -var project_name=${project_name} -var environment=${environment} -auto-approve
    post_build:
        commands:
            - cd $${CODEBUILD_SRC_DIR_SourceGossOutput}
            - terraform destroy -var project_name=${project_name} -var environment=${environment} -auto-approve
artifacts:
    files:
        - '**/*'