version: 0.2

env:
    variables:
        CODE_SRC_DIR: "."

phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - stat $${CODEBUILD_SRC_DIR_SourceAnsibleOutput}/init.sh && bash $${CODEBUILD_SRC_DIR_SourceAnsibleOutput}/init.sh $${CODEBUILD_SRC_DIR_SourceAnsibleOutput} || echo "No init.sh script found"
            - apt-get install -y jq curl unzip
            - curl -s -qL -o mitogen.tar.gz https://files.pythonhosted.org/packages/source/m/mitogen/mitogen-${mitogen_version}.tar.gz
            - mv mitogen.tar.gz /opt; cd /opt; tar vxzf mitogen.tar.gz
            - curl -s -qL -o packer.zip https://releases.hashicorp.com/packer/${packer_version}/packer_${packer_version}_linux_amd64.zip
            - unzip -o packer.zip
            - mv packer /bin
            - rm packer.zip
    build:
        commands:
            - echo "Configuring AWS credentials"
            - echo "Fetching AWS credentials from ECS metadata service"
            - echo "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI}"
            - curl -qL -o aws_credentials.json http://169.254.170.2/$${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI} > aws_credentials.json
            - aws configure set region $AWS_REGION
            - aws configure set aws_access_key_id `jq -r '.AccessKeyId' aws_credentials.json`
            - aws configure set aws_secret_access_key `jq -r '.SecretAccessKey' aws_credentials.json`
            - aws configure set aws_session_token `jq -r '.Token' aws_credentials.json`
            - echo "Building HashiCorp Packer template, ${packer_config}"
            - cd $${CODEBUILD_SRC_DIR}/$${CODE_SRC_DIR}
            - /bin/packer init ${packer_config}
            - ln -s $${CODEBUILD_SRC_DIR_SourceAnsibleOutput}/roles
            - /bin/packer build -var project_name=${project_name} -var environment=${environment} -var ansible_roles=$${CODEBUILD_SRC_DIR_SourceAnsibleOutput}/roles ${packer_config}
    post_build:
        commands:
            - cd $${CODEBUILD_SRC_DIR}/$${CODE_SRC_DIR}
            - test -s ami_id.txt || exit 1
artifacts:
    files:
        - '**/*'