version: 0.2

env:
    variables:
        CODE_SRC_DIR: "."

phases:
    build:
        commands:
            
            - curl -qL -o aws_credentials.json http://169.254.170.2/$${AWS_CONTAINER_CREDENTIALS_RELATIVE_URI} > aws_credentials.json
            - aws configure set region $AWS_REGION
            - aws configure set aws_access_key_id `jq -r '.AccessKeyId' aws_credentials.json`
            - export AWS_ACCESS_KEY_ID=`jq -r '.AccessKeyId' aws_credentials.json`
            - aws configure set aws_secret_access_key `jq -r '.SecretAccessKey' aws_credentials.json`
            - export AWS_SECRET_ACCESS_KEY=`jq -r '.SecretAccessKey' aws_credentials.json`
            - aws configure set aws_session_token `jq -r '.Token' aws_credentials.json`
            - export AWS_SESSION_TOKEN=`jq -r '.Token' aws_credentials.json`
            - echo "Building HashiCorp Packer template, ${packer_config}"
            - cd $${CODEBUILD_SRC_DIR}/$${CODE_SRC_DIR}
            - /bin/packer build -var project_name=${project_name} -var ansible_dir=$${CODEBUILD_SRC_DIR_SourceAnsibleOutput} ${packer_config}
    post_build:
        commands:
            - cd $${CODEBUILD_SRC_DIR}/$${CODE_SRC_DIR}
            - test -s ami_id.txt || exit 1
artifacts:
    files:
        - '**/*'

cache:
  paths:
    - '/root/.config/**/*'
    - '/root/.local/**/*'
    - '/bin/packer'