version: 0.2

env:
    variables:
        CODE_SRC_DIR: "."

phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - which pip3 || curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
            - which pip3 || python3 get-pip.py --user
            - stat $(python -m site --user-base)/bin/ansible-playbook || python3 -m pip install --user ansible pywinrm
            - stat $(python -m site --user-base)/bin/ansible-playbook || exit 1
            - stat /bin/packer || curl -s -qL -o packer.zip https://releases.hashicorp.com/packer/${packer_version}/packer_${packer_version}_linux_amd64.zip
            - stat /bin/packer || unzip -o packer.zip
            - stat /bin/packer || $(mv packer /bin && rm packer.zip)

    build:
        commands:
            - /bin/packer init ${packer_config}

artifacts:
    files:
        - '/root/.config/**/*'
        - '/root/.local/**/*'
        - '/root/.local/bin/**/*'
        - '/bin/packer'

cache:
  paths:
    - '/root/.config/**/*'
    - '/root/.local/**/*'
    - '/root/.local/bin/**/*'
    - '/bin/packer'