name: "ModTest"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - dev
    
jobs:
  modtest:
    uses: HappyPathway/centralized-actions/.github/workflows/modtest.yml@main
    with:
       workspace: ${{ vars.test_workspace }}
       github_server: github.com 
       github_org: ${{ vars.GH_ORG }}
       mod_source: image-pipeline/aws
       branch: ${{ github.head_ref }}
