name: "Terraform"

on:
  workflow_dispatch:
  pull_request:
    
jobs:
  terraform:
    uses: HappyPathway/terraform-validate@main
    with:
      terraform_version: 1.9.1
      terraform_api: app.terraform.io
      terraform_token: ${{ secrets.TFE_TOKEN }}
